# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ravi's blog 
email: ravinaik1312@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This website is just a test of a couple of new technologies I am playing with.  
  The twitter and github links are of some random(but awesome!) guy who I am big fan of. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: ravi1312
github_username:  ravinaik1312

# Build settings
markdown: kramdown
